### PR TITLE
(Bug report) u_buy_item error

### PR DESCRIPTION
**Pull request by Maryionet**
Screenshot_2022-05-22-10-25-51-17_6fe8938556442e3d4f710ab4f9a16601

### CODE REVIEW

**Comment by Maryionet** [comment]
I've managed to fix the u_buy_errors but i encountered numerous errors in the dda version

**Comment by Maryionet** [comment]
Like this
Screenshot_2022-05-22-14-57-48-23_6fe8938556442e3d4f710ab4f9a16601

**Comment by Zlorthishen** [comment]
> I've managed to fix the u_buy_errors but i encountered numerous errors in the dda version

what did you change?

>Like this

That file isn't needed, and I deleted it. What other errors are you encountering?

**Comment by Maryionet** [comment]
> > I've managed to fix the u_buy_errors but i encountered numerous errors in the dda version
> 
> what did you change?
> 
> > Like this
> 
> That file isn't needed, and I deleted it. What other errors are you encountering?

I've replaced the u_buy_item with the u_spawn_item this is the jsons that have the u_buy errors.
TALK_MAQUIS_CHAD_ERIKSON.json, TALK_MAQUIS_MOTH_MUTANT.json, TALK_MAQUIS_MECHANIC.json, TALK_RANDY_ERIKSON.json, TALK_REFUGEE_RANDY_ERIKSON.json
And i encountered errors in the alien fauna, xenoid, and stray jsons but i managed to fixed it by copying it's counterpart jsons on kennan's modpack

**Comment by Maryionet** [comment]
Also here's the types of the errors that i've discovered
Screenshot_2022-05-23-11-38-31-66_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-08-33-95_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-07-48-33_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-39-38-41_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-39-28-68_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-39-14-06_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-39-01-03_6fe8938556442e3d4f710ab4f9a16601
Screenshot_2022-05-23-11-38-43-09_6fe8938556442e3d4f710ab4f9a16601

**Comment by Maryionet** [comment]
Screenshot_2022-05-23-11-44-01-38_6fe8938556442e3d4f710ab4f9a16601

**Comment by Maryionet** [comment]
Note that this not an exhausted list of errors that i've showed.

**Pull request closed without merging**
